name: quote command

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 1,3,5'
env:
  SLACK_WEBHOOK_LANG: ${{ secrets.SLACK_WEBHOOK_LANG }}
  X_RAPID_API_KEY: ${{ secrets.X_RAPID_API_KEY }}
  IS_LOCAL: false
jobs:
  quote:
    name: sends a spanish quote to Slack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - run: go run ./cmd/quotes/main.go
